#+STARTUP: indent
#+OPTIONS: H:4
#+bind: org-export-publishing-directory "~/org/exports"
#+AUTHOR: Zxy
#+EMAIL: gcoordinate@gmail.com
#+TITLE: Readme for translate-emacs-toolkit

* WHATE IS TRANSLATE-EMACS-TOOLKIT FOR
  This toolkit contains several emacs elisp file which help to
  translate by translate api. Now it support bing translate api
  and youdao translate api.

  It provides support for *translate region and input*, *show
  translate history* and so on.

  This toolkit tested on emacs23.4.
  
* USAGE
** For bing translate api
1. Install [[http://www.gnu.org/software/emacs/][emacs]].
2. Add bing-translate-api.el to emacs's load-path.
3. Add the following codes to .emacs file.
   #+begin_src emacs-lisp
(add-to-list 'load-path (concat git-path "translate-emacs-toolkit"))

;; Your appId. Application at http://www.bing.com/toolbox/bingdeveloper/
(defvar bingtranslate-appId "your-appId")

;; Your priority language to translate from.
(defvar bingtranslate-from-priority "en")

;; Your priority language to translate to.
(defvar bingtranslate-to-priority "zh-CHS")

(require 'bing-translate-api)

;; key bounding
(global-set-key [M-f1] 'bingtranslate-region-or-input)

;; add a pair of language
;; Parameters: "pair name" "from language" "to language"
;; All language codes and names at:
;; http://www.emreakkas.com/internationalization/microsoft-translator-api-languages-list-language-codes-and-names
(bingtranslate-add-pair "1" "zh-CHS" "en")
   #+end_src
   Plugin-path is the folder path where translate-emacs-toolkit
   is.
4. Restart emacs and /M-x bingtranslate-region-or-input/. Input
   text, from languge and to language. Then translation result
   is in minibuffer and shear plate.
5. /M-x bingtranslate-show-history/ will show translate history
   at a temp buffer.
** For youdao translate api
1. Install [[http://www.gnu.org/software/emacs/][emacs]].
2. Add youdao-translate-api.el to emacs's load-path.
3. Add the following codes to .emacs file.
   #+begin_src emacs-lisp
(add-to-list 'load-path (concat git-path "translate-emacs-toolkit"))
(defvar youdaotranslate-keyfrom "your-keyfrom")
(defvar youdaotranslate-key "your-key")
(require youdao-translate-api)
   #+end_src
   Plugin-path is the folder path where translate-emacs-toolkit
   is.
4. Restart emacs and /M-x youdaotranslate-region-or-input/. Input
text, from languge and to language.
5. /M-x youdaotranslate-show-history/ will show translate history
at a temp buffer.
* MORE INFORMATION
You can find more information at the project website
http://code.google.com/p/translate-emacs-toolkit/.

And my chinese blog
http://coordinate.sinaapp.com/?p=157.

* LICENSE
This toolkit is licensed under the GPL v3.

* AUTHOR'S WORDS 
If you find a bug, please post at [[https://code.google.com/p/appengine-emacs-toolkit/issues/list][Issues]]. If you have not find a
bug and feel this project helpful, please star it. Every star can
make me know what I do can help other people and drove me forward.

